name: SonarCloud Pull Request Decoration
on: [pull_request]
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Docker Compose
        run: docker-compose --env-file=env/.env.local up -d

      - name: Update Packages
        run:
          sudo apt-get update

      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
#      - name: Checkout Branch
#        uses: actions/checkout@v3
#        with:
#          fetch-depth: '0'
      - name: Retrieve pull request HEAD ref
        id: retrieve_pr_head_ref
        run: |
          IFS='/'
          
          read -r -a strarr1 <<< "$SOURCE_REPO_FULL_NAME"
          sourceRepoOwner="${strarr1[0]}"
          sourceRepoName="${strarr1[1]}"
          fullHeadRef="${strarr1[0]}:${SOURCE_BRANCH_NAME}"
          echo sourceRepoOwner "$sourceRepoOwner" sourceRepoName "$sourceRepoName"
          
          read -r -a strarr2 <<< "$TARGET_REPO_FULL_NAME"
          targetRepoOwner=${strarr2[0]}
          targetRepoName="${strarr2[1]}"
          echo targetRepoOwner "$targetRepoOwner" targetRepoName "$targetRepoName"
          
          if [ "$targetRepoOwner" == "$sourceRepoOwner" ]
          then
              echo using source branch name "$SOURCE_BRANCH_NAME"
              echo "headRef=$SOURCE_BRANCH_NAME" >> "$GITHUB_OUTPUT"
          else
              echo using full head ref "$fullHeadRef"
              echo "headRef=$fullHeadRef" >> "$GITHUB_OUTPUT"
          fi
        env:
          SOURCE_REPO_FULL_NAME: ${{ github.event.pull_request.head.repo.full_name }}
          TARGET_REPO_FULL_NAME: ${{ github.event.pull_request.base.repo.full_name }}
          SOURCE_BRANCH_NAME: ${{ github.head_ref }}

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
#          SOURCE_BRANCH_NAME: ${{ github.head_ref }}
          SOURCE_BRANCH_NAME: ${{ steps.retrieve_pr_head_ref.outputs.headRef }}
          TARGET_BRANCH_NAME: ${{ github.base_ref }}
#          SOURCE_BRANCH_FULL_NAME: ${{ github.event.pull_request.head.repo.full_name }}
#          TARGET_BRANCH_FULL_NAME: ${{ github.event.pull_request.base.repo.full_name }}
#          SOURCE_BRANCH_BY_OUTPUT: ${{ steps.retrieve_pr_head_ref.outputs.headRef }}
          POSTGRES_URL: jdbc:postgresql://localhost:5400/banking_kata_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
          MONGO_INITDB_ROOT_USERNAME: rootuser
          MONGO_INITDB_ROOT_PASSWORD: rootpass
          ME_CONFIG_MONGODB_ADMINUSERNAME: rootuser
          ME_CONFIG_MONGODB_ADMINPASSWORD: rootpass
          ME_CONFIG_MONGODB_SERVER: mongodb
          KEYCLOAK_REALM_URL: http://localhost:10000/auth/realms/banking-kata
          KEYCLOAK_TEST_CLIENT_ID: test-client
          KEYCLOAK_TEST_CLIENT_SECRET: B9N1WDFFMuZmYuEzXSbRC739YGaE7kb5
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          REDIS_PASSWORD: b4EA2xC6LlKnlizPu9bwRRrQM
        run: ./gradlew build sonar --info -Dsonar.login=$SONAR_TOKEN -Dsonar.pullrequest.key=$PULL_REQUEST_NUMBER -Dsonar.pullrequest.branch=$SOURCE_BRANCH_NAME -Dsonar.pullrequest.base=$TARGET_BRANCH_NAME
#        run: echo SOURCE_BRANCH_FULL_NAME ${SOURCE_BRANCH_FULL_NAME} SOURCE_BRANCH_BY_OUTPUT ${SOURCE_BRANCH_BY_OUTPUT}